# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  post_install do |installer|
        installer.pods_project.build_configurations.each do |config|
            config.build_settings.delete('CODE_SIGNING_ALLOWED')
            config.build_settings.delete('CODE_SIGNING_REQUIRED')
        end
    end

	pod 'Alamofire', '~> 4.7'
	pod 'AlamofireNetworkActivityIndicator', '~> 2.2'
	pod 'AlamofireImage', '~> 3.5'

	pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.2.0'
	pod 'IQKeyboardManager'
	pod 'RESideMenu', '~> 4.0.7'
	pod 'FCAlertView'
	pod 'NVActivityIndicatorView'
	pod 'HGPlaceholders' , '0.3.0'

 	pod 'Firebase/Core'
 	pod 'Fabric', '~> 1.7.11'
 	pod 'Crashlytics', '~> 3.10.7'

end
